### ISSUE TITLE
I got an error while running the program

### ISSUE THREAD

**Issue by Fluff4life** [Zionekkk/Discord_Server_Cloner_Updated#1]
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/Users/juneychan/Downloads/errr/main.py", line 97, in on_ready
    guild = await client.create_guild("My Server!")
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/client.py", line 1235, in create_guild
    data = await self.http.create_guild(name, region_value, icon)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 10008): Unknown Message
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/gateway.py:509: DeprecationWarning: get_relationship is deprecated.
  func(data)
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/gateway.py:509: DeprecationWarning: get_relationship is deprecated.
  func(data)

**Comment by Zionekkk** [comment]
Creating a new server makes an error, it's because discord isn't allowing it, use the first option instead of the second
